server:
  port: 8092
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${SPRING-CLOUD-EUREKA-ZONE}
  instance:
    hostname: 49.234.223.73
    prefer-ip-address: true
    instanceId: ${eureka.instance.hostname}:${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html

spring:
  application:
    name: wechat-service
  security:
    user:
      name: admin
      password: admin

