server:
  port: 8093
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instanceId: ${eureka.instance.hostname}:${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html

spring:
  application:
    name: fileserver
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://172.17.16.11:3306/team?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: Sakura_336
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 30000
      maximum-pool-size: 10
      minimum-idle: 3
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

paper_path: /paper/

photo_path: /photo/