server:
  port: 8091
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instanceId: ${eureka.instance.hostname}:${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html

spring:
  application:
    name: api
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-ciph06hq.sql.tencentcdb.com:25696/team?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: Sakura_336
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 300000

mybatis-plus:
  mapper-locations: mapper/*.xml

