server:
  port: 8091
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${SPRING-CLOUD-EUREKA-ZONE}
  instance:
    hostname: 49.234.223.73
    prefer-ip-address: true
    instanceId: ${eureka.instance.hostname}:${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html

spring:
  application:
    name: api
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://${SPRING-CLOUD-MYSQL-HOST}/${SPRING-CLOUD-DB-NAME}?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: Sakura_336
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 30000
      maximum-pool-size: 10
      minimum-idle: 3

mybatis-plus:
  mapper-locations: mapper/*.xml

#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE