eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${SPRING-CLOUD-EUREKA-ZONE}

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin