CREATE TABLE IF NOT EXISTS `student` (
    `ID` INT(11) AUTO_INCREMENT COMMENT '主键',
    `USER_ID` VARCHAR(20) NOT NULL COMMENT '用户标识',
    `USER_NAME` VARCHAR(50) NOT NULL COMMENT '用户姓名',
    `CLASS` VARCHAR(20) COMMENT '班级',
    `COLLEGE` VARCHAR(20) COMMENT '学院',
    `CREATE_TIME` datetime COMMENT '创建时间',
    `UPDATE_TIME` datetime COMMENT '更新时间',
    PRIMARY KEY(`ID`)
    )ENGINE = InnoDb DEFAULT CHARSET = utf8