CREATE TABLE IF NOT EXISTS `user`(
    `ID` INT AUTO_INCREMENT COMMENT '主键',
    `USER_ID` VARCHAR(20) NOT NULL COMMENT '用户标识',
    `USER_NAME` VARCHAR(50) NOT NULL COMMENT '用户姓名',
    `USER_PASSWORD` VARCHAR(50) NOT NULL COMMENT '用户密码',
    `USER_TEL` VARCHAR(50) COMMENT '用户电话',
    `USER_EMAIL` VARCHAR(50) COMMENT '用户邮箱',
    `AUTHORITY` INT(11) NOT NULL COMMENT '权限 0为管理员 1为教师 2为学生',
    `CREATE_TIME` DATETIME COMMENT '创建时间',
    `UPDATE_TIME` DATETIME COMMENT '更新时间',
    PRIMARY KEY(`ID`)
    )ENGINE = InnoDb DEFAULT CHARSET = utf8