CREATE TABLE IF NOT EXISTS project(
    `ID` INT(11) AUTO_INCREMENT COMMENT '主键',
    `STUDENT_NAME` VARCHAR(20) COMMENT '学生姓名',
    `TEACHER_NAME` VARCHAR(20) COMMENT '导师姓名',
    `PROJECT` VARCHAR(20) COMMENT '项目名称',
    PRIMARY KEY(`ID`)
    )ENGINE = InnoDb DEFAULT CHARSET = utf8